---
server:
  port: 8888

spring:
  application:
    name: gateway-server
  config:
    import: "file:application-common.yml"
  cloud:
    gateway:
      discovery:
        locator:
          # Enable automatic routing based on service discovery
          enabled: true
          lower-case-service-id: true
      routes:
        - id: task-manager
          uri: lb://task-manager
          predicates:
            - Path=/task-manager/**
          filters:
            - RewritePath=/task-manager/(?<segment>.*), /${segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

springdoc:
  swagger-ui:
    urls:
      - name: task-manager
        url: /task-manager/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
