---
server:
  port: ${server.port:8082}  # can be overridden by `-Dserver.port` VM option

spring:
  application:
    name: user-service
  config:
    import: "file:application-common.yml"
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    url: |
      jdbc:mysql://localhost:3306/task_db?
      useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # Automatically update table structure
    show-sql: true        # show SQL statements
    properties:
      hibernate:
        format_sql: true  # format SQL statements

springdoc:
  swagger-ui:
    path: /docs           # Access URL becomes http://localhost:8080/docs
    use-root-path: false
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false

eureka:
  instance:
    # Use the INSTANCE_ID passed via JVM to identify different instances.
    # Default to <application-name>-<random-value>.
    instance-id: ${INSTANCE_ID:${spring.application.name}-${random.value}}
